<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sourabhdh-w7" name="Tests [editUserGroup]" tests="1" failures="0" timestamp="15 Dec 2016 07:00:40 GMT" time="107.005" errors="0">
  <testcase name="@AfterMethod afterMethod" time="0.0" classname="com.test.AdminTest">
    <failure type="java.io.FileNotFoundException" message=".\src\main\resources\Automation Test Execution Sheet.xlsm (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.io.FileNotFoundException: .\src\main\resources\Automation Test Execution Sheet.xlsm (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at com.ideator.common.WorkBookRead.writeSheetTDD(WorkBookRead.java:40)
	at com.ideator.util.PageClass.teardown(PageClass.java:156)
	at com.test.AdminTest.afterMethod(AdminTest.java:125)
	at com.test.Ideator_Start.testNgRun(Ideator_Start.java:41)
	at com.test.Ideator_Start.main(Ideator_Start.java:100)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod afterMethod -->
  <testcase name="@AfterClass afterClass" time="0.0" classname="com.test.AdminTest">
    <skipped/>
  </testcase> <!-- @AfterClass afterClass -->
  <testcase name="editUserGroup" time="53.915" classname="com.test.AdminTest"/>
</testsuite> <!-- Tests [editUserGroup] -->
