<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Saurabh-PC" name="Tests [createNewIdea, ]" tests="1" failures="1" timestamp="20 Nov 2016 08:24:07 GMT" time="190.426" errors="0">
  <testcase name="LoginNormalUser" time="15.216" classname="com.test.PublicUser">
    <failure type="java.lang.AssertionError" message="expected [https://ucsdtest.ideator.com/ideas?after_login=true] but found [https://ucsdtest.ideator.com/sign_in]">
      <![CDATA[java.lang.AssertionError: expected [https://ucsdtest.ideator.com/ideas?after_login=true] but found [https://ucsdtest.ideator.com/sign_in]
	at com.test.PublicUser.LoginNormalUser(PublicUser.java:44)
	at com.test.IdeatorStart.testNgRun(IdeatorStart.java:49)
	at com.test.IdeatorStart.main(IdeatorStart.java:114)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- LoginNormalUser -->
</testsuite> <!-- Tests [createNewIdea, ] -->
